version: '3.8'
services:
  alphavantage-simulator:
    ports: 
      - "8081:8080"
    image: "org.ignast.stock-investing.quotes/alphavantage-simulator:1.0-SNAPSHOT"
  mysql-dev:
    ports:
      - "3306:3306"
    image: "org.ignast.stock-investing.quotes/mysql-dev:1.0-SNAPSHOT"
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
