version: '3.7'
services:
  alphavantage-simulator:
    ports: 
      - "8080:8080"
    image: "org.ignast.stock-investing.quotes/alphavantage-simulator:1.0-SNAPSHOT"
  mysql-dev:
    ports:
      - "3306:3306"
    image: "org.ignast.stock-investing.quotes/mysql-dev:1.0-SNAPSHOT"
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
  quotes-app:
    ports:
      - "8081:8081"
    image: "org.ignast.stock-investing.quotes/quotes-service:1.0-SNAPSHOT"
